### ISSUE TITLE
tip: don't use absolute paths

### ISSUE THREAD

**Issue by TorchedSammy** [Rachithooda/Tkinter-Music-Player#1]
[This here](https://github.com/Rachithooda/Tkinter-Music-Player/blob/ab1095f6983d1da480d609d4d99ac95978ef6b0d/main.py#L50) is an absolute path and unless you don't want users (or yourself on a different machine) setting up this specific directory you should use a relative path. `./assets/music.ico` for example will be more portable.

**Comment by Rachithooda** [comment]
@TorchedSammy 
yeah I know that can I use `./assets/music.ico` but this project of mine is very old that I have uploaded on github few day ago at that time I was learning python and thinker but now I use relative path only .

**Comment by TorchedSammy** [comment]
oh okay good, but you can still update this right

**Comment by Rachithooda** [comment]
@TorchedSammy I have made the changes
